# Modelling

Menggunakan algoritma Random Forest Classifier

In [1]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [2]:
# Read data
df = pd.read_csv("ground_vi_data.csv")
df.head()

date hemispherical   longitude  latitude   region  ndre_karet   
0  19/01/22    IMG_3761_2  104.541217 -2.925328  1-bpm24    0.179929  \
1  19/01/22    IMG_3754_2  104.541035 -2.925307  1-bpm24    0.186941   
2  19/01/22    IMG_3746_2  104.541010 -2.925442  1-bpm24    0.182272   
3  19/01/22    IMG_3737_2  104.541267 -2.925553  1-bpm24    0.188025   
4  19/01/22    IMG_3731_2  104.541405 -2.925567  1-bpm24    0.178248   

   lci_karet  ndre_gulma  lci_gulma  severity_level  
0   0.263949    0.230401   0.332627               2  
1   0.282940    0.241650   0.353368               3  
2   0.266318    0.227874   0.333177               3  
3   0.278577    0.238956   0.347100               2  
4   0.266711    0.232217   0.337075               2

In [ ]:
# # Function for ML Report Classification
# def ml_report_classification(model, X_train, y_train, X_test, name):
#     print("====================\n" + name + "\n====================\n")
#     scores = cross_val_score(model, X_train, y_train, cv=5)
#     print("List Traning Scores :", scores)
#     print("Training Average : {} +- {}".format(scores.mean(), scores.std()))
#     print("Validation Score\n----------------------\n")
#     y_pred = model.predict(X_test)
#     print("Accuracy Score :", accuracy_score(y_pred, y_test))
#     print("F1-Score       :", f1_score(y_pred, y_test, average='macro'))
#     print(classification_report(y_pred, y_test))
#     print(confusion_matrix(y_pred, y_test))

In [3]:
df.shape

(144, 10)

In [4]:
# Check missing values
df.isnull().sum()

date              0
hemispherical     0
longitude         0
latitude          0
region            0
ndre_karet        0
lci_karet         0
ndre_gulma        0
lci_gulma         0
severity_level    0
dtype: int64

In [5]:
# Extract data for 1-3 level
df123 = df[df.severity_level < 4]
df123.shape

(132, 10)

In [6]:
X = np.array(df123[['ndre_karet', 'lci_karet']])
y = np.array(df123['severity_level'])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=123)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((105, 2), (27, 2), (105,), (27,))

In [38]:
lr = LogisticRegression(random_state=0)
rf = RandomForestClassifier(random_state=0, n_estimators=200)
scores_rf = cross_val_score(rf, X_train, y_train, cv=5, scoring='accuracy')
scores_lr = cross_val_score(lr, X_train, y_train, cv=5, scoring='accuracy')
scores_rf.mean(), scores_rf.std()

(0.45714285714285713, 0.11895234282663616)

In [9]:
scores_lr.mean(), scores_lr.std()

(0.4, 0.15822140691272524)

In [39]:
rf.fit(X_train, y_train)
ypred = rf.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, ypred))
print(confusion_matrix(y_test, ypred))

              precision    recall  f1-score   support

           1       0.80      0.50      0.62         8
           2       0.42      0.50      0.45        10
           3       0.50      0.56      0.53         9

    accuracy                           0.52        27
   macro avg       0.57      0.52      0.53        27
weighted avg       0.56      0.52      0.53        27

[[4 3 1]
 [1 5 4]
 [0 4 5]]


In [36]:
from sklearn.svm import SVC
svm = SVC(kernel='rbf', random_state=0)
scores_svm = cross_val_score(svm, X_train, y_train, cv=5, scoring='accuracy')
scores_svm.mean(), scores_svm.std()

(0.47619047619047616, 0.06734350297014738)

In [37]:
svm.fit(X_train, y_train)
ypred = svm.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, ypred))
print(confusion_matrix(y_test, ypred))

              precision    recall  f1-score   support

           1       0.60      0.75      0.67         8
           2       0.00      0.00      0.00        10
           3       0.47      0.89      0.62         9

    accuracy                           0.52        27
   macro avg       0.36      0.55      0.43        27
weighted avg       0.33      0.52      0.40        27

[[6 0 2]
 [3 0 7]
 [1 0 8]]


/home/iqballm09/Documents/skripsi/code/env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/iqballm09/Documents/skripsi/code/env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/iqballm09/Documents/skripsi/code/env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo